fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall.git
  symlinks:
    spacewalk: "#{source_dir}"
